### ISSUE TITLE
add topic tags

### ISSUE THREAD

**Issue by Beliavsky** [AntonioRochaAZ/Basic-Optimization-Framework---FORTRAN-90#1]
I suggest adding the topics `numerical-optimization`, `gradient-descent` in the About section, as described at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics

**Comment by AntonioRochaAZ** [comment]
Thank you for the suggestion! I don't master all of GitHub's functionalities. It is done :)
Feel free to make more suggestions!
